# Generated by Django 3.1.3 on 2020-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201113_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url_image',
            field=models.URLField(blank=True),
        ),
    ]
