# Generated by Django 3.1.3 on 2020-11-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201113_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_title',
            new_name='title',
        ),
    ]
