# Generated by Django 3.1.3 on 2020-11-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201114_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
