# Generated by Django 3.1.3 on 2020-11-21 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201121_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
