# Generated by Django 3.1.3 on 2020-11-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_last_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='last_bid',
        ),
    ]
